import json

with open(r'c:\Users\Lenovo\Desktop\E.Events\frontend\src\locales\se.js', 'r', encoding='utf-8') as f:
    content = f.read()

start = content.index('JSON.parse("') + len('JSON.parse("')
end = content.rindex('")')
json_str = content[start:end]
wrapped = '"' + json_str + '"'
decoded = json.loads(wrapped)
data = json.loads(decoded)

# Translation dictionary: Swedish value -> Swahili value
# For string values only; array values keep structure but translate string parts
sw_translations = {
    # Key translations provided
    "- Klicka för att publicera": "- Bonyeza Kuchapisha",
    "- Klicka för att avpublicera": "- Bonyeza Kufuta Uchapishaji",
    "'There\\'s nothing to show yet'": "'Hakuna kitu cha kuonyesha bado'",
    "incheckad": "ameingia",
    "utcheckad": "ametoka",
    "tillgängliga": "zinapatikana",
    "skapades framgångsrikt": "imeundwa kwa mafanikio",
    "uppdaterades": "imesasishwa kwa mafanikio",
    "incheckade": "walioingia",
    "dagar": "siku",
    "timmar": "masaa",
    "minuter": "dakika",
    "sekunder": "sekunde",
    "och": "na",
    "s första evenemang": "s tukio la kwanza",
    "Active Webhooks": "Webhooks Zinazofanya Kazi",
    "available": "zinapatikana",
    "created successfully": "imeundwa kwa mafanikio",
    "left": "zilizobaki",
    "logo": "nembo",
    "organizers": "waandaaji",
    "tickets": "tiketi",
    "updated successfully": "imesasishwa kwa mafanikio",
    "checked in": "walioingia",
    "of {totalCount} available": "kati ya {totalCount} zinazopatikana",
    "days, hours, minutes, and seconds": "siku, masaa, dakika, na sekunde",
    "events": "matukio",
    "hours, minutes, and seconds": "masaa, dakika, na sekunde",
    "minutes and seconds": "dakika na sekunde",
    "first event": "tukio la kwanza",
    "ticket types": "aina za tiketi",
    "About": "Kuhusu",
    "About Stripe Connect": "Kuhusu Stripe Connect",
    "Absorb fee": "Chukua ada",
    "Absorb Fee": "Chukua Ada",
    "Accent Color": "Rangi ya Msisitizo",
    "Accept": "Kubali",
    "Accept bank transfers": "Kubali uhamisho wa benki",
    "Accept credit card payments": "Kubali malipo ya kadi ya mkopo",
    "Accept invitation": "Kubali mwaliko",
    "Accept Invitation": "Kubali Mwaliko",
    "Access Denied": "Ufikiaji Umekataliwa",
    "Account": "Akaunti",
    "Account already connected!": "Akaunti tayari imeunganishwa!",
    "Account configuration updated successfully": "Mipangilio ya akaunti imesasishwa kwa mafanikio",
    "Account Information": "Taarifa za Akaunti",
    "Account Name": "Jina la Akaunti",
    "Account not found": "Akaunti haikupatikana",
    "Account Settings": "Mipangilio ya Akaunti",
    "Account updated successfully": "Akaunti imesasishwa kwa mafanikio",
    "Accounts": "Akaunti",
    "Actions": "Vitendo",
    "Activate": "Washa",
    "Activation date": "Tarehe ya uanzishaji",
    "Active": "Inafanya kazi",
    "Active Events": "Matukio Yanayofanya Kazi",
    "Add": "Ongeza",
    "Add New": "Ongeza Mpya",
    "Add Option": "Ongeza Chaguo",
    "Add Product": "Ongeza Bidhaa",
    "Add Question": "Ongeza Swali",
    "Add Tax or Fee": "Ongeza Kodi au Ada",
    "Add tickets": "Ongeza tiketi",
    "Add to Calendar": "Ongeza kwenye Kalenda",
    "Add Webhook": "Ongeza Webhook",
    "Additional Fees": "Ada za Ziada",
    "Additional Information": "Taarifa za Ziada",
    "Address": "Anwani",
    "Address Line 1": "Mstari wa Anwani 1",
    "Address Line 2": "Mstari wa Anwani 2",
    "Admin": "Msimamizi",
    "Admin Dashboard": "Dashibodi ya Msimamizi",
    "Admin users have full access": "Watumiaji wasimamizi wana ufikiaji kamili",
    "Affiliate": "Mshirika",
    "Affiliates": "Washirika",
    "All Archived Events": "Matukio Yote Yaliyohifadhiwa",
    "All attendees": "Washiriki wote",
    "All Ended Events": "Matukio Yote Yaliyokwisha",
    "All Events": "Matukio Yote",
    "All Products": "Bidhaa Zote",
    "All Upcoming Events": "Matukio Yote Yanayokuja",
    "Allow": "Ruhusu",
    "Amount": "Kiasi",
    "Appearance": "Muonekano",
    "Apply": "Tumia",
    "Archive": "Hifadhi",
    "Archived": "Imehifadhiwa",
    "Attendee": "Mshiriki",
    "Attendees": "Washiriki",
    "Back": "Rudi",
    "Background Color": "Rangi ya Mandharinyuma",
    "Cancel": "Ghairi",
    "Cancelled": "Imeghairiwa",
    "Capacity": "Uwezo",
    "Categories": "Makundi",
    "Category": "Kundi",
    "Check in": "Ingia",
    "Check out": "Toka",
    "Checkout": "Malipo",
    "City": "Mji",
    "Close": "Funga",
    "Code": "Nambari",
    "Color": "Rangi",
    "Colors": "Rangi",
    "Completed": "Imekamilika",
    "Confirm": "Thibitisha",
    "Confirm Password": "Thibitisha Nenosiri",
    "Connect": "Unganisha",
    "Continue": "Endelea",
    "Copy": "Nakili",
    "Country": "Nchi",
    "Create": "Unda",
    "Create Event": "Unda Tukio",
    "Create new": "Unda mpya",
    "Create Organizer": "Unda Mwandaaji",
    "Created": "Imeundwa",
    "Currency": "Sarafu",
    "Current Password": "Nenosiri la Sasa",
    "Customer": "Mteja",
    "Dashboard": "Dashibodi",
    "Date": "Tarehe",
    "Date and Time": "Tarehe na Wakati",
    "Delete": "Futa",
    "Description": "Maelezo",
    "Details": "Maelezo",
    "Discount": "Punguzo",
    "Download": "Pakua",
    "Draft": "Rasimu",
    "Edit": "Hariri",
    "Email": "Barua pepe",
    "Email address": "Anwani ya barua pepe",
    "End Date": "Tarehe ya Mwisho",
    "Ended": "Imekwisha",
    "English": "Kiingereza",
    "Error": "Hitilafu",
    "Event": "Tukio",
    "Events": "Matukio",
    "Export": "Hamisha",
    "Fee": "Ada",
    "Fees": "Ada",
    "Filter": "Chuja",
    "First Name": "Jina la Kwanza",
    "Fixed": "Imara",
    "Free": "Bure",
    "French": "Kifaransa",
    "General": "Jumla",
    "German": "Kijerumani",
    "Get started": "Anza",
    "Go back": "Rudi nyuma",
    "Gross sales": "Mauzo ya jumla",
    "Guests": "Wageni",
    "Have a promo code?": "Una nambari ya promosheni?",
    "Hidden": "Imefichwa",
    "Homepage": "Ukurasa wa Nyumbani",
    "Inactive": "Haifanyi kazi",
    "Invoice": "Ankara",
    "Label": "Lebo",
    "Language": "Lugha",
    "Last Name": "Jina la Mwisho",
    "Loading...": "Inapakia...",
    "Location": "Mahali",
    "Log in": "Ingia",
    "Logging in": "Inaingia",
    "Login": "Ingia",
    "Logout": "Toka",
    "Manage": "Simamia",
    "Message": "Ujumbe",
    "Messages": "Ujumbe",
    "My Profile": "Wasifu Wangu",
    "Name": "Jina",
    "New Password": "Nenosiri Jipya",
    "No": "Hapana",
    "No events to show": "Hakuna matukio ya kuonyesha",
    "No results": "Hakuna matokeo",
    "Notes": "Maelezo",
    "Notifications": "Arifa",
    "Online Event": "Tukio la Mtandaoni",
    "Optional": "Hiari",
    "Order": "Agizo",
    "Orders": "Maagizo",
    "Organizer": "Mwandaaji",
    "Organizers": "Waandaaji",
    "Padding": "Nafasi",
    "Password": "Nenosiri",
    "Payment": "Malipo",
    "Percentage": "Asilimia",
    "Phone": "Simu",
    "Price": "Bei",
    "Products": "Bidhaa",
    "Profile": "Wasifu",
    "Promo Code": "Nambari ya Promosheni",
    "Publish": "Chapisha",
    "Questions": "Maswali",
    "Refund": "Rudisha pesa",
    "Register": "Jisajili",
    "Reports": "Ripoti",
    "Required": "Inahitajika",
    "Reset Password": "Weka upya Nenosiri",
    "Revenue": "Mapato",
    "Save": "Hifadhi",
    "Search": "Tafuta",
    "Send": "Tuma",
    "Settings": "Mipangilio",
    "Sign up": "Jisajili",
    "Sold Out": "Imeisha",
    "Start Date": "Tarehe ya Kuanza",
    "Status": "Hali",
    "Submit": "Wasilisha",
    "Success": "Mafanikio",
    "Support": "Msaada",
    "Tax": "Kodi",
    "Taxes": "Kodi",
    "Ticket": "Tiketi",
    "Tickets": "Tiketi",
    "Time": "Wakati",
    "Title": "Kichwa",
    "Total": "Jumla",
    "Type": "Aina",
    "Update": "Sasisha",
    "Upload": "Pakia",
    "User": "Mtumiaji",
    "Users": "Watumiaji",
    "View": "Angalia",
    "Waitlist": "Orodha ya Kusubiri",
    "Welcome": "Karibu",
    "Yes": "Ndiyo",
    "Your password": "Nenosiri lako",
    "Zip/Postal Code": "Nambari ya Posta",
    "Don't have an account?": "Huna akaunti?",
    "Already have an account?": "Una akaunti tayari?",
    "Forgot password?": "Umesahau nenosiri?",
    "Welcome back": "Karibu tena",
    "Sign in to your account": "Ingia kwenye akaunti yako",
    "Create your account": "Unda akaunti yako",
    "Enter your credentials to continue": "Ingiza vitambulisho vyako kuendelea",
    "Start selling tickets in minutes": "Anza kuuza tiketi kwa dakika chache",
    "New here?": "Mpya hapa?",
    "Create an account": "Unda akaunti",
    "Sign in": "Ingia",
    "Send link": "Tuma kiungo",
    "Just looking for your tickets?": "Unatafuta tiketi zako tu?",
    "Check your inbox!": "Angalia kisanduku chako cha barua pepe!",
    "Try another email": "Jaribu barua pepe nyingine",
    "Swahili": "Kiswahili",
    "Event management & ticketing platform": "Jukwaa la usimamizi wa matukio na tiketi",
    "Sell tickets. Grow your events.": "Uza tiketi. Kukuza matukio yako.",
    "The all-in-one platform for event creators": "Jukwaa kamili kwa waundaji wa matukio",
    "Powered by": "Inaendeshwa na",
    "Save Changes": "Hifadhi Mabadiliko",
    "Changes saved": "Mabadiliko yamehifadhiwa",
    "Something went wrong": "Kuna tatizo lililotokea",
    "Please try again": "Tafadhali jaribu tena",
    "Confirm email": "Thibitisha barua pepe",
    "Verify Email": "Thibitisha Barua Pepe",
    "Verifying...": "Inathibitisha...",
    "Check your email": "Angalia barua pepe yako",
    "Resend code": "Tuma tena nambari",
    "Resend in": "Tuma tena baada ya",
    "Didn't receive the code?": "Hukupokea nambari?",
    "Set up your organization": "Weka shirika lako",
    "Create your first event": "Unda tukio lako la kwanza",
    "What type of event?": "Ni aina gani ya tukio?",
    "Event name": "Jina la tukio",
    "Start date & time": "Tarehe na wakati wa kuanza",
    "End time (optional)": "Wakati wa kumalizia (hiari)",
    "Continue Setup": "Endelea na Usanidi",
    "Creating Event...": "Inaunda Tukio...",
    "Skip this step": "Ruka hatua hii",
    "About & Support": "Kuhusu na Msaada",
    "User Management": "Usimamizi wa Watumiaji",
    "Upcoming": "Yanayokuja",
    "Past": "Yaliyopita",
    "View on Google Maps": "Angalia kwenye Google Maps",
    "Get Directions": "Pata Maelekezo",
    "View Map": "Angalia Ramani",
    "Share": "Shiriki",
    "Contact": "Wasiliana",
    "Contact organizer": "Wasiliana na mwandaaji",
    "Tickets Available": "Tiketi Zinapatikana",
    "Join from anywhere": "Jiunge kutoka popote",
    "This event has ended": "Tukio hili limekwisha",
}
